import type { Metadata } from 'next';
import './globals.css';
import LocaleContext from './i18n/LocaleContext';
import { FbtResult, IntlVariations, setupFbtee } from 'fbtee';
import { ja_JP } from '../translations/ja_JP.json';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = (await cookies()).get('NEXT_LOCALE')?.value ?? 'en_US';
  setupFbtee({
    hooks: {
      getViewerContext: () => ({
        GENDER: IntlVariations.GENDER_UNKNOWN,
        locale,
      }),
    },
    translations: {
      ja_JP,
    },
  });

  return (
    <html lang="en">
      <body>
        <LocaleContext>{children}</LocaleContext>
      </body>
    </html>
  );
}
